version: '3.8'

services:

  database:
    image: mysql:8.0.25
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lportal
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE --lower-case-table-names=0
    volumes:
       - ./mysql-dump:/docker-entrypoint-initdb.d
    cap_add:
       - SYS_NICE
    ports:
      - "3306:3306"

  liferay:
    image: liferay/dxp:7.4.13-u65
    environment:
      - LIFERAY_JVM_OPTS=-Xms2g -Xmx4g
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://database/lportal?characterEncoding=utf8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=root
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=root
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY=20
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES=5
      - LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED=false
      - LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_LOCALE=en_US
      - LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_TIME_PERIOD_ZONE=UTC-3
      - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_SEND_PERIOD_PASSWORD_PERIOD_RESET_PERIOD_LINK=false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_CUSTOM_PERIOD_QUESTION_PERIOD_ENABLED=false
      - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_UPDATE_PERIOD_PASSWORD_PERIOD_REQUIRED=false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PRIVATE_PERIOD_LAYOUTS_PERIOD_AUTO_PERIOD_CREATE=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PRIVATE_PERIOD_LAYOUTS_PERIOD_ENABLED=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PUBLIC_PERIOD_LAYOUTS_PERIOD_AUTO_PERIOD_CREATE=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PUBLIC_PERIOD_LAYOUTS_PERIOD_ENABLED=false
      - LIFERAY_BLOGS_PERIOD_PINGBACK_PERIOD_ENABLED=false
      - LIFERAY_BLOGS_PERIOD_PING_PERIOD_GOOGLE_PERIOD_ENABLED=false
      - LIFERAY_COM_PERIOD_LIFERAY_PERIOD_PORTAL_PERIOD_SHAREPOINT_PERIOD__UPPERCASES_HAREPOINT_UPPERCASEF_ILTER=false
      - LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED=false
      - LIFERAY_LOCALES=pt_BR,es_ES,en_US
      - LIFERAY_LOCALES_PERIOD_ENABLED=pt_BR,es_ES,en_US
      - LIFERAY_SESSION_PERIOD_TRACKER_PERIOD_MEMORY_PERIOD_ENABLED=false
      # - LIFERAY_HIBERNATE_PERIOD_JDBC_PERIOD_BATCH_UNDERLINE_SIZE=200
      # - LIFERAY_BUFFERED_PERIOD_INCREMENT_PERIOD_STANDBY_PERIOD_QUEUE_PERIOD_THRESHOLD=10000
      # - LIFERAY_BUFFERED_PERIOD_INCREMENT_PERIOD_STANDBY_PERIOD_TIME_PERIOD_UPPER_PERIOD_LIMIT=60
      # - LIFERAY_COUNTER_PERIOD_INCREMENT=5000
      - LIFERAY_DL_PERIOD_STORE_PERIOD_IMPL=com.liferay.portal.store.file.system.AdvancedFileSystemStore
      # - LIFERAY_DATABASE_PERIOD_INDEXES_PERIOD_UPDATE_PERIOD_ON_PERIOD_STARTUP=true
      # - LIFERAY_UPGRADE_PERIOD_DATABASE_PERIOD_AUTO_PERIOD_RUN=true
      - LIFERAY_DISABLE_TRIAL_LICENSE=true
    ports:
      - "8080:8080"
      - "11311:11311"
    volumes:
      - ./liferay-deploy:/mnt/liferay/deploy
      - ./liferay-files:/mnt/liferay/files
      - ./liferay-document-library:/opt/liferay/data/document_library
    depends_on:
      - database
      - search

  search:
    image: elasticsearch:8.6.2
    environment:
      - cluster.name=LiferayElasticsearchCluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "node.name=es-node1"